import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Layout from '../components/layout/layout'
import { getSortedPostsData } from '../utils/post.utils'

export type HomeProps = {
  posts: ReturnType<typeof getSortedPostsData>
}

const Home: NextPage<HomeProps> = ({ posts }) => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="w-full h-full">
        <h1 className="text-4xl font-bold text-teal-500">
          Read my <Link href="/posts/first-post">Post</Link>
        </h1>

        <section className="w-full h-full mt-8">
          <ul className="flex flex-col items-center justify-center gap-4">
            {posts.map((post) => (
              <li key={post.id} className="w-full">
                <h3>
                  <Link href={`/posts/${post.id}`}>{`${post.title} ${post.date}`}</Link>
                </h3>
              </li>
            ))}
          </ul>
        </section>
      </main>
    </Layout>
  )
}

export default Home

export async function getStaticProps() {
  const posts = getSortedPostsData()

  return {
    props: { posts },
  }
}
